import React, {useState} from "react";
import './form.css'

const FormEx3 = () => {
    const [formState, setFormState] = useState({
        firstName: '',
        lastName: ''
    })

    const onChangeHandler = e => {
        setFormState({
            ...formState, // state must remain immutable, so DO NOT modify previous state, instead here we create a new one
            [e.target.name]: e.target.value, // here we add new property with the name, we use the name because later we will work with autogenerated ids, so here we use the name
        });
    };

    const onSubmitHandler = e => {
        // IMPORTANT:
        e.preventDefault(); // This will instruct the browser not to run its standard event code for this event,
        // in this case, preventDefault() will avoid reloading the page and changing the url when the form is submitted (which is standard event code for submit form event).
        // These actions would reset our React state, and that is not something we want.
        console.log(formState);
    };

    return (
        <form onSubmit={onSubmitHandler}>
            <label htmlFor="firstName">First Name</label>
            <input id="firstName"
                   name="firstName"
                   onChange={onChangeHandler}
                   value={formState.firstName}/>
            <label htmlFor="lastName">Last Name</label>
            <input id="lastName"
                   name="lastName"
                   onChange={onChangeHandler}
                   value={formState.lastName}/>
            <button type="submit">Save</button>
        </form>
    );
};

export default FormEx3;