import React, {useState} from "react";
import './form.css'

const FormEx2 = () => {
    const [formState, setFormState] = useState({
        firstName: '',
        lastName: ''
    })

    const onChangeHandler = e => {
        setFormState({
            ...formState, // state must remain immutable, so DO NOT modify previous state, instead here we create a new one
            [e.target.name]: e.target.value, // here we add new property with the name, we use the name because later we will work with autogenerated ids, so here we use the name
        });
    };

    return (
        <form>
            <spam>{`Your name is: ${formState.firstName} ${formState.lastName}`}</spam>
            <br/>
            <label htmlFor="firstName">First Name</label>
            <input id="firstName"
                   name="firstName"
                   onChange={onChangeHandler}
                   value={formState.firstName}/>
            <label htmlFor="lastName">Last Name</label>
            <input id="lastName"
                   name="lastName"
                   onChange={onChangeHandler}
                   value={formState.lastName}/>
        </form>
    );
};

export default FormEx2;