import React, {useState} from "react";
import './form.css'

const initialState = {
    firstName: '',
    lastName: '',
    bio: ''
};

const FormEx5 = () => {
    const [formState, setFormState] = useState(initialState)

    const onChangeHandler = e => {
        setFormState({
            ...formState, // state must remain immutable, so DO NOT modify previous state, instead here we create a new one
            [e.target.name]: e.target.value, // here we add new property with the name, we use the name because later we will work with autogenerated ids, so here we use the name
        });
    };

    const onSubmitHandler = e => {
        // IMPORTANT:
        e.preventDefault(); // This will instruct the browser not to run its standard event code for this event,
        // in this case, preventDefault() will avoid reloading the page and changing the url when the form is submitted (which is standard event code for submit form event).
        // These actions would reset our React state, and that is not something we want.
        console.log(formState);
    };

    const onClickHandler = () => {
        setFormState(initialState);
    };

    return (
        <form onSubmit={onSubmitHandler}>
            <label htmlFor="firstName">First Name</label>
            <input id="firstName"
                   name="firstName"
                   onChange={onChangeHandler}
                   value={formState.firstName}/>
            <label htmlFor="lastName">Last Name</label>
            <input id="lastName"
                   name="lastName"
                   onChange={onChangeHandler}
                   value={formState.lastName}/>
            <label htmlFor="bio">Bio</label>
            <textarea id="bio"
                      name="bio"
                      rows="10"
                      onChange={onChangeHandler}
                      value={formState.bio}/>
            <button type="submit">Save</button>
            <button type="button" onClick={onClickHandler}>Clear values</button>
        </form>
    );
};

export default FormEx5;